version: '3'

services:
  # Kotlin
  Kotlin-DI:
    image: ubuntu
    container_name: kotlin_DI
    tty: true
    volumes:
      - ./src/main/kotlin:/var/kotlin
    ports:
      - "8080:80"
      - "10022:22"
    network_mode: "sample-network5"

networks:
  sample-network5: